# Generated by Django 4.0.4 on 2022-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpellBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_player', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lvl_spell', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='photos/<django.db.models.fields.CharField>')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
