# Generated by Django 4.0.4 on 2022-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0002_choice_question_delete_spellbook_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_spell', models.CharField(max_length=30)),
                ('lvl', models.IntegerField(default=0, max_length=2)),
                ('school', models.CharField(max_length=20)),
                ('cast_time', models.CharField(max_length=20)),
                ('time_spell', models.CharField(max_length=40)),
                ('components', models.CharField(max_length=50)),
                ('class_user', models.CharField(max_length=30)),
                ('text', models.TextField()),
            ],
        ),
    ]
