# Generated by Django 4.0.4 on 2022-04-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0003_spellbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=30)),
            ],
        ),
    ]
